spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ekallavya/spring-boot-global-data-config
          username: 
          password: 
        bootstrap: true
server:
  port: 8888


